#include "lib/dma.h"

dmac_descriptor_registers_t DMAC_DESCRIPTORS[DMA_CH_COUNT];
dmac_descriptor_registers_t _DMAC_WRITE_BACK_DESCRIPTORS[DMA_CH_COUNT];

extern "C" {
	void DMAC_0_Handler() {
		auto chint {DMAC_REGS->DMAC_CHINTFLAG};
		DMAC_REGS->DMAC_CHINTFLAG = 0xff;
	}
}


void dma::initI2C() {
	DMAC_REGS->DMAC_BASEADDR = 
					DMAC_REGS->DMAC_WRBADDR = (uint32_t) DMAC_DESCRIPTORS;
	DMAC_REGS->DMAC_CTRL = DMAC_CTRL_LVLEN0(1)
					| DMAC_CTRL_DMAENABLE(1);
	
	DMAC_REGS->DMAC_CHID = 0;
	DMAC_REGS->DMAC_CHCTRLB = DMAC_CHCTRLB_TRIGACT_BLOCK
					| DMAC_CHCTRLB_TRIGSRC_SERCOM0_TX;
	
	DMAC_REGS->DMAC_CHINTENSET = DMAC_CHINTENSET_TCMPL(1) | DMAC_CHINTENSET_TERR(1);
	NVIC_EnableIRQ(DMAC_0_IRQn);
	
	DMAC_DESCRIPTORS[DMA_CH_I2C_TX].DMAC_BTCTRL = DMAC_BTCTRL_BEATSIZE_BYTE
					| DMAC_BTCTRL_VALID(1);
}
